### ISSUE TITLE
Vector Z Missing

### ISSUE THREAD

**Issue by rocammo** [pagoru/PlaneSimulatorX#1]
![zvector](https://cloud.githubusercontent.com/assets/9489977/19869744/e7af004c-9fad-11e6-8039-d440e2c826c9.png)
El "ISSUE" se encuentra en el paquete 'es.pagoru.planesimulatorx.utils' en la clase 'Vector3Di'. Falta añadir en el método add() el vector Z, ( que imagino que se te habrá colado, ;-) ).

Saludos de un seguidor tuyo.

**Comment by pagoru** [comment]
[utils.Vector3Di.java](https://github.com/pagoru/PlaneSimulatorX/blob/master/src/es/pagoru/planesimulatorx/utils/Vector3Di.java)

``` JAVA
public Vector3Di add(Vector3Di vector){
        this.x += vector.x;
        this.y += vector.y;
        return this;
}
```
